config/routes.rb
Rails.application.routes.draw do

  resources :characters
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/character.rb
class Character < ApplicationRecord
  validates :nome,
    presence: true
    uniqueness: true
  validates :str, :agi, :res,
    presence: true
    numericality: true
    if: :EstaDentroDoLimite?

  def EstaDentroDoLimite?
    str + agi + res <= 10
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/characters_controller.rb
class CharactersController < ApplicationController
  def new
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/characters_helper.rb
module CharactersHelper
end

app/views/characters/new.html.erb
<h1>Crie seu personagem</h1>

<%= form_for :Character, url: characters_path do |f| %>
  <p>
    <%= f.label "Nome:" %>
    <%= f.text_field :nome %><br />
    <%= f.label "Força: " %>
    <%= f.text_field :for %>
    <%= f.label "Resistência: " %>
    <%= f.text_field :res %>
    <%= f.label "Agilidade: " %>
    <%= f.text_field :agi %><br>
    A soma dos atributos não deve ultrapassar 10.
  </p>

  <p>
    <%= f.submit %>
  </p>
  <% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>EP3</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>